class_name UIEnums

enum UI {
	MAIN_MENU,
	SETTINGS_MENU,
	PAUSE_MENU,
	PLAYER_HUD,
	CHICKEN_INVENTORY,
	POULTRYMAN_SHOP,
	POULTRYMAN_SHOP_CONFIRMATION,
	DEATH_SCREEN,
	VICTORY_SCREEN,
	IN_ARENA_SHOP,
	PLAYER_DEBUG_MENU,
	ROUND_SCREEN,
	LOADING_SCREEN,
	CHICKEN_STATS,
	FORFEIT_POPUP,
	REBIRTH_SHOP,
	DIALOGUE_BALLOON,
	DELETE_SAVE_POPUP
}

const PATHS: Dictionary[UI, String] = {
	UI.MAIN_MENU: "uid://dab0i61vj1n23",
	UI.SETTINGS_MENU: "uid://81fy3yb0j33w",
	UI.PAUSE_MENU: "uid://dnq3em8w064n4",
	UI.PLAYER_HUD: "uid://xhakfqnxgnrr",
	UI.CHICKEN_INVENTORY: "uid://dvkxcgdk0goul",
	UI.POULTRYMAN_SHOP: "uid://bir1j5qouane0",
	UI.POULTRYMAN_SHOP_CONFIRMATION: "uid://da6m7g6ijjyop",
	UI.DEATH_SCREEN: "uid://ba8j8ajmddtai",
	UI.VICTORY_SCREEN: "uid://sjvml6sgskxh",
	UI.IN_ARENA_SHOP: "uid://djg6luy3rxi23",
	UI.PLAYER_DEBUG_MENU: "uid://bjr4b02aehry4",
	UI.ROUND_SCREEN: "uid://61l26wjx0fux",
	UI.LOADING_SCREEN: "uid://cu2ima27whcct",
	UI.CHICKEN_STATS: "uid://c2vh7na31m8hi",
	UI.FORFEIT_POPUP: "uid://bqt3s2usixpf3",
	UI.REBIRTH_SHOP: "uid://dmgeue4l6fj4f",
	UI.DIALOGUE_BALLOON: "uid://cfg06xxv1turn",
	UI.DELETE_SAVE_POPUP : "uid://fgrmwyv0t0py"
}

## List of UI elements that should block game input outside of the UI
const UI_BLOCK_GAME_INPUT: Array[UI] = [
	UI.SETTINGS_MENU,
	UI.PAUSE_MENU,
	UI.CHICKEN_INVENTORY,
	UI.POULTRYMAN_SHOP,
	UI.POULTRYMAN_SHOP_CONFIRMATION,
	UI.DIALOGUE_BALLOON,
	UI.IN_ARENA_SHOP,
	UI.ROUND_SCREEN,
	UI.LOADING_SCREEN,
	UI.REBIRTH_SHOP,
	UI.DEATH_SCREEN,
	UI.CHICKEN_STATS,
	UI.FORFEIT_POPUP
]


static func ui_to_string(ui: UI) -> String:
	return UI.keys()[ui]
